import Head from "next/head";
import { Inter } from "next/font/google";
import HomeComponent from "./Components/HomeComponent";
import { MdDiscount, MdLocalShipping, MdPayments } from "react-icons/md";
import { MdLabelImportant } from "react-icons/md";
import { BsCurrencyDollar } from "react-icons/bs";
import { BsAwardFill } from "react-icons/bs";
import { MdSupportAgent } from "react-icons/md";
import { FaPlane } from "react-icons/fa";
import CustomStyle from './CSSfile/FoodProductStyle.module.css'
import AboutEcommarse from "./Components/AboutEcommarse";
import ShopByBrandsSlider from "./Components/ShopByBrandsSlider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Ecommarse Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          type="text/css"
          charset="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </Head>
      <main>
        <div
          style={{
            width: "100%",
            overflow: "hidden",
            position: "relative",
          }}
        >
          <HomeComponent></HomeComponent>
        </div>
        <div style={{background: '#05b4ef'}} className="px-3 py-8 lg:px-12 md:px-8 ">
          <AboutEcommarse></AboutEcommarse>
        </div>

        <div>
          <ShopByBrandsSlider></ShopByBrandsSlider>
        </div>
      </main>
    </>
  );
}
